### ISSUE TITLE
Cannot see module in OpenERP 7!

### ISSUE THREAD

**Issue by ghost** [openlabs/magento_integration#100]
Hi!

I’m trying to get the OpenERP Module to work.

I downloaded the zip from github. I extracted it to my OpenERP addons path. I then ran python setup.py install.

I logged in to my OpenERP site. I updated the module list. But I cannot see the module in the list of over 200 modules.

What am I doing wrong?

Please help!

Thanks.

**Comment by lighthere** [comment]
Go to Settings->Modules->Installed Modules and then clear the "Installed" filter from the search box. Then you will see ALL modules and not only Apps

**Comment by KevEd** [comment]
Same problem as fosstux, have tried re-installing adjusting all variants of Administrator settings but the new module does not appear whatever search, filtering or Advanced search I try.
There is a Blog thread on this subject where several people are having same problem with their own Modules.
http://acespritechblog.wordpress.com/2012/12/05/how-to-install-new-module-in-openerp-7-0/

**Comment by KevEd** [comment]
I looked at the file 'base_quality_interrogation.py'  It lists criteria for modules which includes the user name and password as admin, does this mean that the module viewer will only accept new modules if they're installed while using the default username/password? I've set up a new Administrator and password account (as any security conscious user would do) - has the module viewer not been tested with fresh admin accounts?

**Comment by shalabhaggarwal** [comment]
@KevEd The blog you have mentioned above has no relation to this module. This is a completely different module.

For this module you should follow the instructions provided at https://openerp-magento-connector.readthedocs.org/en/develop/introduction.html#installation

**Comment by KevEd** [comment]
Yes, the module is different but the problem with OpenERP is the same.
I and the support at my hosting provider have both followed the
instructions twice with same outcome.

Regards,
Kevin

**Comment by shalabhaggarwal** [comment]
@KevEd Can you make sure that the openerp user you are using has `Technical Features` enabled?

**Comment by KevEd** [comment]
Hi,
Yes the technical features box is checked on the admin account.
Has the install been tested on an account which does not have admin/admin
credentials? It looks like there's a config file which has database and
password hard coded in (which, I think, is why it works for you but not
others).

**Comment by ghost** [comment]
I've now reinstelled OpenERP on a Debian Server using apt-get.

This leaves me with 4 addons directories:
- /usr/share/pyshared/openerp/tests/addons
- /usr/share/pyshared/openerp/addons
- /usr/lib/pymodules/python2.6/openerp/tests/addons
- /usr/lib/pymodules/python2.6/openerp/addons

What is the right path for the magento_integration addon?

**Comment by shalabhaggarwal** [comment]
@fosstux You should check the openerp server's configuration file and use the addons path provided in that file.

**Comment by KevEd** [comment]
Hi shalabhaggarwal, is the advice you gave fosstux relevant to the problem I am having too? I have found one server config file which contains a user and password (both 'admin') and a server address - do I need to edit this config file (or another config file) to use my server path and db user details?
If I do need to manually edit any files, can you specify where to find them please? I've followed the standard install instructions and not moved or altered any files.

**Comment by shalabhaggarwal** [comment]
Hi @KevEd , if you can check the server logs of openerp, it states the configuration file being used when the server starts. You need to put the module in the addons path mentioned in that file.

**Comment by KevEd** [comment]
Hi, can you clarify this please - when you say 'Server starts' do you mean
the main Ubuntu/Apache server or is there part of OpenERP which is called
'server?
Do I need to restart the host server to generate a log?

Thanks.

**Comment by KevEd** [comment]
UPDATE:  My hosting admin has increased the memory limit which has enabled
more modules to appear in the OpenERP app list. When I search for 'Magento'
there are some modules which are called 'Product Many Categories' and
Product Image list' which, I think they are for another Magento module
rather than the OpenLabs app.

When we identify the config file and edit it - I'm hopeful the correct
Magento module will appear.

**Comment by KevEd** [comment]
Update #2:
I have read the contents of setup.py in the Magento module directory in the
OpenERP addons directory, it metions Postgre but not MySQL. My server does
not use Postgre as far as I know.

excerpt from 'setup.py'

#!/usr/bin/env python

# -_\- coding: UTF-8 -_-

'''
    Magento Integration module setup

```
:copyright: (c) 2010-2013 by Openlabs Technologies & Consulting (P) LTD
:license: AGPLv3, see LICENSE for more details
```

'''
import os
import sys
import unittest
from setuptools import setup, Command

class TravisTest(Command):
    """
    Run the tests on Travis CI.

```
Travis CI offers database settings which are different
"""
description = "Run tests on Travis CI"

user_options = []

def initialize_options(self):
    pass

def finalize_options(self):
    pass

def run(self):
    from openerp.tools import config
    config.options['db_user'] = 'postgres'
    config.options['db_host'] = 'localhost'
    config.options['db_port'] = 5432
    parent_folder, current_folder = os.path.dirname(
        os.path.abspath(__file__)
    ).rsplit('/', 1)
    config.options['addons_path'] += ',' + parent_folder
    from tests import suite
    test_result = unittest.TextTestRunner(verbosity=3).run(suite())

    if test_result.wasSuccessful():
        sys.exit(0)
    sys.exit(-1)
```

**Comment by KevEd** [comment]
Hi,
my server is running OpenERP on Postgre. Module still doesn't appear.

Regards,
Kevin

**Comment by ghost** [comment]
I'm still having the same problem.

Any further ideas?

Thanks.
Christopher

**Comment by sharoonthomas** [comment]
seems more like an openerp issue rather than an issue with this module

**Comment by premjawariya** [comment]
Just give 777 permission on the module folder problem will be solved.

**Comment by sharoonthomas** [comment]
@premjawariya for the record (future visitors to the page) having 777 permissions is a bad idea and is the first step into having all kind of security issues.
