### ISSUE TITLE
UOM NOT FOUND

### ISSUE THREAD

**Issue by diiman2000** [openlabs/magento_integration#101]
I GET THIS ERROR WHEN I TRY TO IMPORT CATALOG
Please define Default Product UOM for website 92trade 
PLS HELP

**Comment by shalabhaggarwal** [comment]
As the error indicates, there is a field for `Default Product UoM` on magento website which are imported from Magento to Openerp. You should configure the same.

**Comment by diiman2000** [comment]
That's the issue.. There is no field for default UOM on magneto. I have checked and could not find anything.

**Comment by shalabhaggarwal** [comment]
This field does not exist on Magento. Its on the imported website in Openerp.

**Comment by diiman2000** [comment]
That's exactly the problem. When my site was imported, there was no UOM defined. The field was blank. Meaning it was supposed to import the UOM from magneto which it did not. It will be helpful if you can tell me where to define UOM on magneto.

**Comment by dstags-LO** [comment]
I had the same issue. To fix it, you have to do the following:

1) Click (in OpenERP) top menu 'Magento' then under configuration click 'Website'
2) Select the website record you want to import the catalog for
3) Click 'Edit' to modify the record. 
4) Select or create a new entry for the 'Default Product UOM'. 
5) Save the record
6) click 'Import Catalog button'

**Comment by shalabhaggarwal** [comment]
@diiman2000 Can you please marked the issue as resolved if the solution provided by @dstags-LO worked for you?

@dstags-LO Thanks for the details explanation.

**Comment by shalabhaggarwal** [comment]
Closing this issue.

Feel free to reopen if needed.
