### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jersobh** [openlabs/magento_integration#103]
Hi guys, 
I'm trying to install this module, but i have some problems:
1. I can only install if i rename the folder to "magento" instead of "magento_integration"
   2.First i couldn't import websites: got an error message, then i re-installed the module, now i get "invalid api"

**Comment by shalabhaggarwal** [comment]
@jersobh You should NOT rename the module magento_integration to anything else. Please follow all the instructions as defined here https://openerp-magento-connector.readthedocs.org/en/develop/introduction.html#installation

`magento` is a separate python module available at https://github.com/openlabs/magento 
This a python module which is a dependency of the openerp module.

Ideally it should be installed automatically when you do `python setup.py install` from inside `magento_integration`.

**Comment by jersobh** [comment]
I think that is the problem, i think pip installs this module instead. I've
ran setup.py from magento_integration.

2013/8/12 Shalabh Aggarwal notifications@github.com

**Comment by jersobh** [comment]
This is my log when i run setup.py

root@wanger:/opt/openerp/7.0/addons/magento_integration# python setup.py
installrunning install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support
.pth files
running bdist_egg
running egg_info
writing requirements to magento_integration.egg-info/requires.txt
writing magento_integration.egg-info/PKG-INFO
writing top-level names to magento_integration.egg-info/top_level.txt
writing dependency_links to
magento_integration.egg-info/dependency_links.txt
reading manifest file 'magento_integration.egg-info/SOURCES.txt'
writing manifest file 'magento_integration.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no
Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/PKG-INFO ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/SOURCES.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/dependency_links.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/not-zip-safe ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/requires.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/top_level.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/magento_integration-0.1-py2.7.egg' and adding
'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing magento_integration-0.1-py2.7.egg
removing
'/usr/local/lib/python2.7/dist-packages/magento_integration-0.1-py2.7.egg'
(and everything under it)
creating
/usr/local/lib/python2.7/dist-packages/magento_integration-0.1-py2.7.egg
Extracting magento_integration-0.1-py2.7.egg to
/usr/local/lib/python2.7/dist-packages
magento-integration 0.1 is already the active version in easy-install.pth

Installed
/usr/local/lib/python2.7/dist-packages/magento_integration-0.1-py2.7.egg
Processing dependencies for magento-integration==0.1
Searching for pycountry==0.18
Best match: pycountry 0.18
Processing pycountry-0.18-py2.7.egg
pycountry 0.18 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pycountry-0.18-py2.7.egg
Searching for magento==0.4
Best match: magento 0.4
Processing magento-0.4-py2.7.egg
magento 0.4 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg
Searching for itsbroken==0.2
Best match: itsbroken 0.2
Processing itsbroken-0.2-py2.7.egg
itsbroken 0.2 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/itsbroken-0.2-py2.7.egg
Searching for suds==0.4.1
Best match: suds 0.4.1
Adding suds 0.4.1 to easy-install.pth file

2013/8/12 Jefferson Andrade jersobh@gmail.com

**Comment by shalabhaggarwal** [comment]
The module and its dependencies seem to be getting installed just fine.

**Comment by shalabhaggarwal** [comment]
Closing this issue.

Feel free to reopen if needed.
