### ISSUE TITLE
Order import creates duplicate customer entries

### ISSUE THREAD

**Issue by gracine** [openlabs/magento_integration#108]
When I import orders from Magento the Customer appears 3 times. One time as a Company and two times as a Partner.

**Comment by Marijn86** [comment]
We have seen this issue as well. In our case, all 3 names/addresses are completely identical, and the order is not from a company.

**Comment by iamniels** [comment]
We have exactly this problem too. Three identical customers are created for each imported order.

**Comment by shalabhaggarwal** [comment]
Magento sends a customer with two addresses, one being billing address and other shipment address, both of which can be different. Also the contacts on both the addresses can be different from the actual customer itself, which essentially gives us three entities to handle.

OpenERP has abolished the concept of multiple addresses per partner and everything has been merged with partner  which makes this a bit tricky to implement in a generic manner.

So we create a partner for the customer and the addresses are created as children partners of the same partner/customer. So in case where all the details are same, it would identical records.

I hope this explains the behaviour.

**Comment by sharoonthomas** [comment]
Here's a funny presentation about how openerp got its contact management wrong.

http://www.slideshare.net/RaphalValyi/open-erp-v7-contacts-issue

I am closing the ticket since its not a "bug" but a "feature" of openerp.

**Comment by sharoonthomas** [comment]
http://www.slideshare.net/RaphalValyi/open-erp-v7-contacts-issue
