### ISSUE TITLE
cant import orders magento to openerp

### ISSUE THREAD

**Issue by jaybeerivera02** [openlabs/magento_integration#112]
im trying to import sale on openerp magento integration.im suing openerpv7 and latest version of magento.

ive got this error message:

"Not Found!

Magento Store Main Website Store should have a shop configured."

is there something i need to configure?

or what?

thanks

**Comment by janpfischer** [comment]
Hello,

yes, you need to configure your Company in OpenERP to the Magento Store.

To do that go in the magento configuration menu in OpenERP.
Click on Website Stores and click on the Website Store you want to become orders from.

Then you have to edit this Website Store view. There is a field Sales Shop. Select your OpenERP Company there. 

I had the same problem. I doesnt find that in Doc. Had to figure it out.

Hope this helps.

**Comment by jaybeerivera02** [comment]
Hi,

Thanks a lot for your help.. 

now its working fine.

one more problem is updating the quantity number of imported products.

**Comment by shalabhaggarwal** [comment]
@jaybeerivera02 Please refer to #81 for the discussion about the quantity import.

**Comment by jaybeerivera02** [comment]
woh.. thanks..@shalabhaggarwal

**Comment by faridghanchi** [comment]
Dear b1rdhous3,

Thanks for the answer.
