### ISSUE TITLE
OpenERP Warning  Incorrect API Settings

### ISSUE THREAD

**Issue by samarSiat** [openlabs/magento_integration#114]
hi
I installed the magento_integration module on openerp7 and I created a new instance .
I also installed Magento core API extension on magento
when I test connexion , an openerp warning appears :
"Incorrect API Settings!Please check and correct the API settings on instance."
I installet magento from http://davidtsadler.com/archives/2012/06/03/how-to-install-magento-on-ubuntu/#php
wait for help!!

**Comment by janpfischer** [comment]
Hi
do you have add an XML-RPC User in Magento?

**Comment by samarSiat** [comment]
hi,
thank you for your answer.
how can i add  a XML-RPC User in Magento?
thank you.

**Comment by janpfischer** [comment]
In Magento Backend go to System ->  Web Services ->SOAP/XML-RPC User.

Adding a user there should be self explaining. 

Hope this helps

**Comment by samarSiat** [comment]
:( the same problem.
I added the user the SOAP/XML-RPC but I still have the  same problem . 
I attached  2 screen print of openerp warning
![1](https://f.cloud.github.com/assets/5338589/1056014/53e3f270-114c-11e3-8de3-1d9dafb4603c.png)
![2](https://f.cloud.github.com/assets/5338589/1056015/5406087e-114c-11e3-90ef-314d9a6bf542.png)

**Comment by janpfischer** [comment]
What configuration did you do on Magento Backenend site? 
will check my configuration later

**Comment by samarSiat** [comment]
the default configuration

**Comment by samarSiat** [comment]
it works .just I forget to add role to the user 
 thank you very much  b1rdhous3 :)

**Comment by ghost** [comment]
I am also getting the same error.I tried all of the above things but it did not help me.
