### ISSUE TITLE
pycountry errors in logs. Do we really need it ?

### ISSUE THREAD

**Issue by capitaine** [openlabs/magento_integration#124]
Does magento_integration needs py.country to work as there is already a country list in openERP ?

These py.country related errors in openerp logs (two for each country) and each time openERP loads:

2013-09-20 07:21:30,312 1048 ERROR ? pycountry.db: Country u'South Georgia and the South Sandwich Islands' already taken in index 'name' and will be ignored. This is an error in the XML databases
...
2013-09-20 07:21:30,328 1048 ERROR ? pycountry.db: Country False already taken in index 'deleted' and will be ignored.

**Comment by sharoonthomas** [comment]
The country list in openerp is as old as openerp itself and has issues with
the country codes being wrong.

The codes used were not ISO codes.

On Saturday, September 21, 2013, capitaine wrote:

> Does magento_integration needs py.country to work as there is already a
> country list in openERP ?
> 
> These py.country related errors in openerp logs (two for each country) and
> each time openERP loads:
> 
> 2013-09-20 07:21:30,312 1048 ERROR ? pycountry.db: Country u'South Georgia
> and the South Sandwich Islands' already taken in index 'name' and will be
> ignored. This is an error in the XML databases
> ...
> 2013-09-20 07:21:30,328 1048 ERROR ? pycountry.db: Country False already
> taken in index 'deleted' and will be ignored.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openlabs/magento_integration/issues/124
> .

## 

## 

Sharoon Thomas
Openlabs Technologies & Consulting (P) Limited

w: http://www.openlabs.co.in
m: +1 813.793.6736 (OPEN) Extn. 200
t: @sharoonthomas
- We Win When our Customers Win

**Comment by capitaine** [comment]
Thank you Thomas for commenting. I understand, but how do we get rid from these errors ? Aren't there any further consequences ?

**Comment by sharoonthomas** [comment]
There are no further consequences. And they are just warnings.

In addition to the usage i explained before it is also used to identify subdivisions.

OpenERP uses a related table to maintain regions/counties/states under a country. While this is the case only states of the USA come bundled with OpenERP. So pycountry is further used to ensure quality data is imported into addresses [1] when customer information comes from magento.

I agree that this is an overhead. It could have been avoided if openerp had come bundled with all countries and states ISO data like it is in Tryton [2].

[1] https://github.com/openlabs/magento_integration/blob/develop/country.py#L114
[2] https://github.com/tryton/country

**Comment by gambolputty** [comment]
I disabled them by setting the log level:

`logging.getLogger("pycountry").setLevel(logging.WARNING)`
