### ISSUE TITLE
Import catalog: not getting the right category from multisite categories tree

### ISSUE THREAD

**Issue by capitaine** [openlabs/magento_integration#126]
Here is the situation in Magento 1.7.02:
1st site: "website1" with "ws1store1" and "ws1st1view1"
2nd site: "website2" with two stores "ws2store1" and "ws2store2" ; "ws2store1" has two views, "ws2store2" has one view.
This is only for documentation, i don't think it has any influence on the problem which is:
Context:
root category for website1: 3 (subcategories 10, 20)
root category for website2: 499 (subcat 510, 520)
- product A belongs to category 499_510 (child category 510 of parent 499)
- product B belongs to categories 3_10 (child 10 of parent 3) and 499_520
  This is the first catalog import, no products (either website1's or website2's) are yet imported.

I'm importing website2's catalog setting root category 499 (in magento instance of OpenERP); 
Result: products A and B are both imported; up so good but...
- the import created categories 510, 520 (right, these are website2 categories) but also 3 and 10 (it shouldn't, these are website1 categories)
- and product B is affected to category 10 instead of 520.

It looks like a difficulty to deal with one-product-to-many-categories
I didn't tested with a single site and product belonging to multiple categories, but it is especially annoying with multisite

**Comment by shalabhaggarwal** [comment]
@capitaine OpenERP by default does not support multiple categories for one product, hence we take only the first category from the list of categories returned by magento for each product. 

Ref: https://github.com/openlabs/magento_integration/blob/develop/product.py#L416

**Comment by capitaine** [comment]
I understand but, in case of a multisite installation, it should be possible to filter categories on a website basis, so only this imported website's categories are created and products even when they belong in multiple categories across multiple sites they will appear under a coherent tree. In the function shown in your ref above, website_obj is already there, could it serve to this ?

Not directly related : in openERP install list of modules there is one called "Product - Many Categories". Could it be a solution ? Do you know if it can work with "Magento integration" ?

**Comment by capitaine** [comment]
I finally managed to run magento_integration but in linux. The windows problem reported in #125 persists. Well, this is not related to this "multisite categories" issue but I can share my happiness here also :)

Beside that there are two new problems:

1) Categories must be unique inside the same instance

So I imported with no problem all products from site A. As I said in the first message, the import created the "undesired" category 10 from site B (at top level while this is not a top level category in Magento. Then came the time for products import from site B. After 2,5 hours of running (there are 4K products), the import ended with this warning "categories must be unique inside the same instance". I suppose this is because openERP met the category 10 (which of course already exits inside openERP since it was created as a collateral effect by the site A's import). 
The import tree was completely imported excepted my category 10. So this category is not in the correct place. Here is what the categories tree looks like inside openERP after the import:

Root Site A/ cat A1/ cat A1.1 (correct)
Roor Site A/ cat A1/ cat A1.2 (correct)
Root Site A/ cat A2 (correct)
cat10 (NOT CORRECT, created by site A import)
Root Site B/ cat B1/ cat B1.1 (correct)
Root site B/ cat B1/ cat B1.2 (correct)
Root site B/ cat B1/ cat 10 (this is the correct place where cat10 should be, but it is NOT IMPORTED)
Root site B/ cat B1/ cat B1.4 (correct)

2) Duplicated products

All my products from site B were imported. 

But now, all products of category10 appear twice with the correct (unique) magento_id. And both ("original" and "duplicated") say they belong to cat10 (the one in top level, the non correct), but when I go to this category (in warehouse > products/products by category) no products show there.

I edited cat10 and put it under its correct place "Root site B/ cat B1/" and now the products appeared but still twice.
Is there a risk to delete the product at Magento side if I delete one of the duplicates in openERP ?

**Comment by shalabhaggarwal** [comment]
If a product is deleted from openerp, it will not be deleted from magento.

If needed, it might be created again when imported next time.

**Comment by capitaine** [comment]
It is impossible to delete any product in openerp which was imported by magento_integration : integrity error (oobject reference: Magento Website - Product store - magento.website.product]). I tried with creating manually a new product with exactly the same info than a magento one (except of course the magento product_id) and this one I was able to delete it.

**Comment by shalabhaggarwal** [comment]
The above issue will be handled by #137
