### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jmsalomr** [openlabs/magento_integration#128]
Hi,

After following the instructions in https://openerp-magento-connector.readthedocs.org/en/develop/introduction.html#installation, when I do:

root@srv20248:/usr/lib/pymodules/python2.7/openerp/addons/magento_integration-develop# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from setuptools import setup, Command
ImportError: No module named setuptools

I get this error. I'm doing something wrong?

Thanks in advance,
Josep

**Comment by shalabhaggarwal** [comment]
@jmsalomr Which OS are you using?

**Comment by sharoonthomas** [comment]
If you are using Ubuntu or any Debian system you can do:

sudo apt-get install python-setuptools

On Saturday, September 21, 2013, jmsalomr wrote:

> Hi,
> 
> After following the instructions in
> https://openerp-magento-connector.readthedocs.org/en/develop/introduction.html#installation,
> when I do:
> 
> root@srv20248:/usr/lib/pymodules/python2.7/openerp/addons/magento_integration-develop#
> python setup.py install
> Traceback (most recent call last):
> File "setup.py", line 13, in
> from setuptools import setup, Command
> ImportError: No module named setuptools
> 
> I get this error. I'm doing something wrong?
> 
> Thanks in advance,
> Josep
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openlabs/magento_integration/issues/128
> .

## 

## 

Sharoon Thomas
Openlabs Technologies & Consulting (P) Limited

w: http://www.openlabs.co.in
m: +1 813.793.6736 (OPEN) Extn. 200
t: @sharoonthomas
- We Win When our Customers Win

**Comment by jmsalomr** [comment]
I'm using Ubuntu 12.04, OpenERP 7.0 and Magento 1.7.0.2.

**Comment by shalabhaggarwal** [comment]
@jmsalomr The advice by @sharoonthomas should do the trick for you. :)

**Comment by jmsalomr** [comment]
Hi. Thanks! this solved the issue. But in OpenERP I cannot see the module. When I went to Update Modules List I got an OpenERP error. After restarting the service (/etc/init.d/openerp start and /etc/init.d/openerp stop) the OpenERP have no errors, but cannot se the module installed.

**Comment by jmsalomr** [comment]
I've tried to repeat the steps, to rename the directory to magento_integration, also change same files, but OpenERP doesn't detect the module.

**Comment by jmsalomr** [comment]
Hi,

Sorry. Solved just looking at issue #100.
