### ISSUE TITLE
Duplicates with (not logged in) customers

### ISSUE THREAD

**Issue by capitaine** [openlabs/magento_integration#134]
So, customers are created as partners while importing orders with one parent (who is / where does he comes from ?) and two children : one for the billing, one for the delivery. That's fine with registered users who then have a magento_id to test for uniqueness. 

The problem is with the "not registered / not logged in" customers, because magento can allow them to place an order. Then it seems to me that magento_integration creates a new customer each time the same "not logged in" customer places an order (and we import it). This produces a profusion of "duplicated" customer records. If a "not logged in" customer places 5 orders, we end up with 5 parents and 10 children. Do we need such a large family? !!!

At first, I thought that we could create a unique generic NotLoggedIn parent and have "delivery" and "billing" children for all the "not logged in" orders under his... authority ! But finally this can't be the solution because of the email address which is part of the parent's data, not of the children ones. I can't see an other solution for the moment, but anyhow we have to find a way to reduce this profusion. Perhaps just a test "if exists" could be enough to stop the colonization.

**Comment by sharoonthomas** [comment]
We are aware about the problem and there is no fool proof (and scalable)  way to confirm that the guest customer in a newly imported order is the same as an existing customer.

If we decide to check everything completely, it would be too slow.

**Comment by capitaine** [comment]
Could we create a some kind of unique parent based on email address and then let his children increase with the number of orders ? We don't stop the children's profusion this way, but we economize some parents. Also, if we want to, let's say, launch a mailing campaign using openERP, we'll avoid to spam the not logged in customers. An other advantage could be that we could list together all orders made by a customer event if he is a "not logged in" one. Currently this is not possible as orders are spread among the various parent clones.

**Comment by shalabhaggarwal** [comment]
We can have a email based identification for the customers being imported but as @sharoonthomas said this will not be a foolproof solutions.

Maybe we can have a user based configuration for this and not make this kind of checking mechanism a default.

@capitaine @sharoonthomas What are your views about it?

**Comment by sharoonthomas** [comment]
@shalabhaggarwal let us target this for 2.0

**Comment by l-arnold** [comment]
May I recomend a "Partner" to be called "Magento Not Logged In" to catch all those orders.  It is quite common to have a "non account" make an order in some situations.  Other than that, it would seem Magento needs to force account creation.

**Comment by nassers** [comment]
after i imported orders, every customer in magento created three times in openERP and in some cases five times (one of them is parent and others are its children). so why this happened?  is it a bug or i did something wrong?

**Comment by sharoonthomas** [comment]
@nassers This presentation should be enlightening about the issue: http://www.slideshare.net/sorryopenerp/open-erp-v7-contacts-issue-23737041
