### ISSUE TITLE
Customer integration issues

### ISSUE THREAD

**Issue by pradeepnew** [openlabs/magento_integration#143]
I followed the steps magento_integration Module Installation issues is fixed. Currently able to Import or Export Product, Order details. But there is no option Customer Details Import or Export. And In the magento_integration module download partner_view.xml file is missing. Is any code available for Import or Export customer details.

**Comment by shalabhaggarwal** [comment]
@pradeepnew We dont see a need for importing or exporting customers explicitly between the two systems. We only import customers along with the orders.

Is there any specific reason why this would be needed?

**Comment by pradeepnew** [comment]
The below requirements we need

1.. Pricelists need to go up from OpenERP to Magento.
2. The Customer ID needs to sync with pricelists in the Magento store so when a pricelist goes up to Magento the customers that have this pricelist applied to them need to link up in Magento also.

How the above functionality work with magento_ntegration module with openerp

**Comment by shalabhaggarwal** [comment]
We already have tier price support but this is customer / customer group agnostic.

For price tiers, you can define price tiers on all the products which would need this. Also you can define default price tiers on **Magento Store** in OpenERP.

These price tiers are just quantities that have to act as tiers for price calculation. We calculate the price corresponding to each tier for each product and this can then be exported to magento

**Comment by pradeepnew** [comment]
How to handle pricelist based on customer basis in openerp currently price tiers based on product quantity

1.. The Customer ID needs to sync with pricelists in the Magento store so when a pricelist goes up to Magento the customers that have this pricelist applied to them need to link up in Magento also.

Please describe

**Comment by sharoonthomas** [comment]
- pricelist does not exist in magento, there are only tier prices
- the concept of pricelist differs completely between openerp and magento

Hence this will not be implemented
