### ISSUE TITLE
Update/Import Products not working in openerp

### ISSUE THREAD

**Issue by pradeepnew** [openlabs/magento_integration#144]
I have deleted some products from magento.

Click on Update Products in openerp it gives following error.
Fault 101: Product not exists

How to Update Products from openerp to magento.

**Comment by shalabhaggarwal** [comment]
Deleting any product from any system is a bad idea. You should always deactivate the products.

Anyway sync on deletion is not supported and will not be supported in future also.

To handle this on your side, you should delete the products manually from OpenERP to prevent the error which comes up.

**Comment by sharoonthomas** [comment]
+1 @shalabhaggarwal

**Comment by pradeepnew** [comment]
How to delete product in openerp in Website screen Magento Products tab
![openerp](https://f.cloud.github.com/assets/5737772/1388976/4fed87c2-3bcb-11e3-8c4a-f17e3c5cec9a.JPG)
