### ISSUE TITLE
Error importing orders ProtocolError for www.test.com/index.php/api/xmlrpc: 500 Internal Server Error

### ISSUE THREAD

**Issue by ragadzi** [openlabs/magento_integration#155]
Hi guys,

My magento installation is setted up with multiple shops and site views, I have successfully installed your connector and I have manage to import all websites, Store Views and Products.

I´m using the latest version of magento and latest version of magento_integration.

When I try to import orders I get this error on 2 of my Store Views:

File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/sales.py", line 34, in list
    return self.call('sales_order.list', [filters])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1312, in single_request
    response.msg,

ProtocolError: "ProtocolError for www.test.com/index.php/api/xmlrpc: 500 Internal Server Error"

---------------------- END OFF ERROR -------------------------------------

On the other shops I get a different error:

File "/opt/openerp/server/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/opt/openerp/server/openerp/addons/magento_integration/magento_.py", line 607, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/opt/openerp/server/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/opt/openerp/server/openerp/addons/magento_integration/sale.py", line 374, in create_using_magento_data
    cursor, user, order_data, context
  File "/opt/openerp/server/openerp/addons/magento_integration/sale.py", line 524, in get_shipping_line_data_using_magento_data
    order_data['shipping_description']
TypeError: sequence item 0: expected string, NoneType found

-------------------- END OFF ERROR -----------------------------

Any help would be greatly appreciated!

**Comment by shalabhaggarwal** [comment]
@ragadzi This would need to be debugged. This seems to be an issue with XML data sent by magento rather than an issue with the connector.

You can debug this yourself at RPC level or you can take professional help.

**Comment by ragadzi** [comment]
Hi shalabhaggarwal,

First of all, thank you for your reply!

The error: 
(order_data['shipping_description']
TypeError: sequence item 0: expected string, NoneType found),  is solved, it was some missing information on magento database.

The xmlrpc: 500 Internal Server Error is related with the big amount of orders to import, around 417000.

Right now, i´m trying to import the orders in little chunks but I have another problem:

In the file magento_.py around line 593 we have the filter dictionary and I want to add two new filters (date range):

```
filter = {
            'store_id': {'=': store_view.magento_id},
            'state': {'in': order_states_to_import_in},
            'created_at': {'gteq': '2013-01-01'}, # new filter
            'created_at': {'lteq': '2013-06-08'}, # new filter
        }
```

this is the many different combinations that I have tried:

```
             #'created_at': {{'gteq': '2013-01-01'}, {'lteq': '2013-06-08'}},
            #'created_at': ['&',{'gteq': '2013-01-01'}, {'lteq': '2013-06-08'}],
            #'created_at': {'gteq': '2013-01-01', 'lteq': '2013-06-08'},
            # ['|',('order_id.user_id','=',user.id),('order_id.user_id','=',False)]
            #'created_at': {'lteq': '2013-08-01 23:59:00'},

           filter2 = {
            'store_id': {'=': store_view.magento_id},
            'state': {'in': order_states_to_import_in},
         'created_at': 
                    { 'from': '2013-07-15 00:00:00',
                      'to': '2013-08-01 23:59:00'}, 
            #'created_at': {'gteq': '2013-07-15'},
        }
```

I also tried with to set of arrays [filter, filter2 ], without success

None of this seems to work!

In PHP I can accomplish the filtering with this method:

$params = array(
           array(
                 'created_at'=>array('gteq'=>'2013-01-01'),
                 'created_at'=>array('lteq'=>'2013-09-31'),
                 'store_id'=>array('eq'=>'23')
)); 

$orders = $xmlrpcclient->call('call', array($session, 'sales_order.list', $params));

How can i do this logic in python? 

I have seen that the function "def list(self, filters=None):"  expects something like:
Format :
                   `{<attribute>:{<operator>:<value>}}`
               Example :
                   `{'firstname':{'ilike':'sharoon'}}`

Best Regards

Pedro Ramos

**Comment by ragadzi** [comment]
Hi shalabhaggarwal,

This problem is solved, this is how I have done (with some help from tecbased):

filter = {
                'store_id': {'=': store_view.magento_id},
                'state': {'in': order_states_to_import_in},
        'created_at':{'from':'2013-01-01', 'to':'2013-06-08'},
            } 

And this also works:

 filter = {
                'store_id': {'=': store_view.magento_id},
                'state': {'in': order_states_to_import_in},
        'created_at':{'gteq':'2013-01-01', 'lteq':'2013-06-08'},
            }

Rigth now, the only problem I have with te module is triplicated clients.

I have tested on different servers (Linux and Windows) both with fresh magento v1.8, openerp 7 and openlabs magento integration (cloned from github) and clean databases (I just made 4 new orders from magento website).

do you think this appens beacouse i´m working with magento version 1.8?

Best Regards,

Pedro Ramos

**Comment by sharoonthomas** [comment]
@ragadzi the partner duplication issue you are talking about is a "openerp v7 feature". http://brochures.sisalp.fr/OpenERP_v7_contacts_issue.pdf

**Comment by sharoonthomas** [comment]
As for the second issue, it is because a large volume of data is loaded in a single attempt and the magento server runs out of memory. 

To avoid this, assuming you are not really interested in all the legacy orders, you could set the Last imported date in the store view in OpenERP and the orders created after that date would be the ones imported.

https://github.com/openlabs/magento_integration/blob/develop/magento_.py#L593
