### ISSUE TITLE
Problem with "Root Categories"

### ISSUE THREAD

**Issue by l-arnold** [openlabs/magento_integration#156]
To my understanding the magento_integration wants the "overall root category" to be specified (normally category 1).  However, if the root category for the Website is specified it will import, but if items are used in multiple category/stores, then multiple copies of products are created in OpenERP.

Magento defines a "root category" to be root category for a Website and does not generally reference the true "root category"
http://www.magentocommerce.com/wiki/3_-_store_setup_and_management/catalog/creating_and_assigning_root_categories

This is further complicated by the fact that some websites will only "import" if there is not a pre-existing "Root Category" as there was in my case.  Renaming to "Old Root" for instance has allowed import...

Best is to  clearly state that the Root is (Magento Root) and that all categories in all websites will be imported in first Website Catalog Import.  The process for product import I was only able to rectify by removing "secondary website" attributes to Magento Products (in Magento) before import as otherwise items were landing one time in various (but not logically grouped Websites and Categories) as I have items often existing in different Websites within Magento.  A linkage with the Multi Category Module in OpenERP would seem to help this, but at present it does not.

**Comment by shalabhaggarwal** [comment]
@l-arnold Multiple copies of products will be created only if the same product is on multiple **websites** of magento. We map the products on both the systems using database IDs. Also as far as my understanding of magento is, each product can be associated with only one website where each website can have multiple stores, store views. Here categories have no role to play.

The root category ID can be anything and all the categories under the same will be imported in tree form. There is no limitation or constraint on what has to be chosen as the root category. Also contrary to products, categories are not limited to websites and are managed on the global/instance level.

As far as linkage with multi category module of openerp is concerned, that is something that can be looked into if there is a standard module in openerp to do so. Can you please provide a link to the module code if there is one?

**Comment by l-arnold** [comment]
In my situation, each product can be assigned to multiple websites just as it can be assigned to multiple categories.  The complication is in whether each store is using "default" values for the product, or if it is using its own.

I try to have each item have shared values (so that it is one item).  

You can easily understand the structure by using "update attributes" pull down in Manage Products in Magento.  You set Inventory once.  You Can assign to various (multiple categories) and you can assign and unassign to multiple websites.

The multiple-category extension for OpenERP can be found in OpenERP by clearing "featured" in Aps, then typing Magento.  Product - Many Catgories  (Sharoon Thomas) 
 Repository
lp:~product-core-editors/openerp-product-attributes/7.0 

the following are also listed 

---

Product - Many CategoriesCommunity
 Install

Product Image GalleryCommunity
 Install

Product Image GalleryCommunity
 Install

Product LinksCommunity
 Install

Sale Automatic WorkflowCommunity
 Install

product_custom_attributesCommunity
 Install

---

Image Gallery and Links seem appropriate.  I don't understand the diff between 7.01 and 7.02 Image Gallery, but that is another subject.  I would recomend getting this application (Magento_Integration) to also show up this way.  I am not clear why it does not, but lets not go into that right now.

Thanks for all your help with this.  I am going to try to post a list of what I would like to see working flow wise.

**Comment by shalabhaggarwal** [comment]
@l-arnold Thanks for the list.

I have created a separate issue to deal with the multiple categories.
Image sync is already a separate issue.
Product attributes is something that we dont see being implemented in this connector.
