### ISSUE TITLE
How to allow Super User (in addition to Admin) access to Magento and Magento Products?

### ISSUE THREAD

**Issue by l-arnold** [openlabs/magento_integration#157]
I saw this is an issue earlier but need to ask for function.

How can I have my normal "self" User in OpenERP have access to Magento Module and Magento created Products?

Nothing seems visible in Settings or elsewhere that I can find.
Thank you,

**Comment by l-arnold** [comment]
I found Issue # 96 but  as I mentioned there, I cannot find a way to this group or how to configure a new one.

You reference this code: <menuitem id="menu_magento" name="Magento"
            sequence="70" groups="base.group_user"/>
        <menuitem id="menu_magento_config" name="Configuration" sequence="50"
            parent="menu_magento" groups="base.group_user"/>

**Comment by l-arnold** [comment]
I just tried to create an ACL  base.group_user" and added it to an Admin Group I am a member of (with all rights), but still same result.  Perhaps I can find "(Document model: magento.website.product) next.  Will delete the ACL just created.

when trying to view a Magento Product I get:
Access Denied

Sorry, you are not allowed to access this document. Please contact your system administrator if you think this is an error.

(Document model: magento.website.product)

**Comment by shalabhaggarwal** [comment]
@l-arnold This is a completely OpenERP related issue.

We have not bundled any ACLs with the module and they can be created by the users as needed.

**Comment by l-arnold** [comment]
I could not find how to make the ACL for base.group_user which is required.  (Why also have the code have a period, then an underline as a separator).

How can one create the required ACL?

**Comment by shalabhaggarwal** [comment]
@l-arnold Please refer to openerp documentation for this.
