### ISSUE TITLE
Exporting stock from last export

### ISSUE THREAD

**Issue by ToRvaLDz** [openlabs/magento_integration#162]
Could be a good idea adding the possibility to update magento stock only for the products that have a stock movement since last export. 
Actually the magento stock update is very slow.

Thank you

**Comment by shalabhaggarwal** [comment]
@ToRvaLDz I agree with the suggestion. Although I am not sure of an efficient and effective way of filtering the products with stock movement since last export.

We can keep this is as feature request and see if this can be implemented.
More suggestions regarding this are welcome.

@sharoonthomas Please attach a suitable tag.

**Comment by ToRvaLDz** [comment]
@shalabhaggarwal looking at the openerp db a query like this could be suitable:

``` sql
with
uitstock as 
( select t.name product, sum(product_qty) sumout, m.product_id, m.product_uom, p.default_code sku from stock_move m 
left join product_product p on m.product_id = p.id 
left join product_template t on p.product_tmpl_id = t.id 
where m.create_date>=$last_import_date and m.company_id=$company_id and m.state like 'done' and m.location_id in (select id from stock_location where complete_name like '%Stock%') and m.location_dest_id not in (select id from stock_location where complete_name like '%Stock%') 
group by product_id,product_uom, t.name, p.default_code order by t.name asc ) ,
instock as 
( select t.standard_price purchaseprice, t.name product, sum(product_qty) sumin, m.product_id, m.product_uom, p.default_code sku from stock_move m 
left join product_product p on m.product_id = p.id 
left join product_template t on p.product_tmpl_id = t.id 
where m.create_date>=$last_import_date and m.company_id=$company_id and m.state like 'done' and m.location_id not in (select id from stock_location where complete_name like '%Stock%') and m.location_dest_id in (select id from stock_location where complete_name like '%Stock%') 
group by product_id,product_uom, t.name, t.standard_price, p.default_code order by t.name asc )

select i.product, i.sku, sumin-coalesce(sumout,0) AS stock, sumin, sumout, purchaseprice, ((sumin-coalesce(sumout,0)) * purchaseprice) as stockvalue from uitstock u full outer join instock i on u.product = i.product 
```

I made a function in php that works but I'm not a python developer.

Hope this can help.

**Comment by omidkosari** [comment]
Our "Export Inventory" takes about 5 hours with 3700 products . It is a critical feature . Let's assume the we have only 1 unit of product_x in stock and a customers buys it directly form store Point of Sale . but the product is still available in Magento . So the "Export Inventory" should done several times in a day which is impossible now .
