### ISSUE TITLE
Export Catlog issue

### ISSUE THREAD

**Issue by shazz0020** [openlabs/magento_integration#163]
Hello folks

Iam facing issues while exporting catlog/products back to magento site.
Note: tested connnection succesfull

Following things i do
Magento->configuration->Website-> i select a website->click on export catalog

Error occurs when-
select Magento Category
select products to export.

error->

  File "/home/shazz/magento/openerp-7.0-dna-motor/openerp/osv/orm.py", line 3656, in _read_flat
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "/home/shazz/magento/openerp-7.0-dna-motor/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/shazz/magento/openerp-7.0-dna-motor/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
  File "/usr/lib/python2.6/dist-packages/psycopg2/extensions.py", line 100, in getquoted
    qobjs = [str(o.getquoted()) for o in pobjs]
AttributeError: 'str' object has no attribute 'getquoted 

Iam not able to trace why iam encountered with this issue
please help me to resolve this issue

Thanks

**Comment by sharoonthomas** [comment]
If this is the full stack trace, then this does not seem to be an issue with the connector. If there is a longer stack trace it might help

**Comment by shazz0020** [comment]
But why am I getting this error??
Any configuration missing ?
can you guide me little bit? Since i could not see error throwing from any .py file so how and where i will put a debugger for tracing?
