### ISSUE TITLE
Pyhon 3.X compatibility

### ISSUE THREAD

**Issue by raeftaker** [openlabs/magento_integration#165]
Hi, like some predecessors I am trying to set-up the system on Windows 7, however during the install-process of this module I am getting the error: 

File "setup.py", line 14, in <module>
    execfile(os.path.join('magento', 'version.py'))
NameError: name 'execfile' is not defined

I am running python 3.3 and after running into this issue, i have tried to follow the steps described here https://github.com/capitaine/magento_integration/blob/patch-1/doc/source/introduction.rst  ... at step 2, installing the magento module, i get a similar error based on execfile ... i would really appreciate any help

**Comment by raeftaker** [comment]
since I didn´t get anywhere with python 3.3 i installed 2.7 .... As intended the installation runs smoothly with 2.7, though a new error close before the finish appears, when i try to "update module list" in the openERP module panel ("ImportError: no module named decimal_precision" see image). Ahh it is really depressing since this is the second day i try to set the connector up ... while separately the programs run great the connector is giving such a headache (at least on my windows 7 machine) 
![importerror](https://f.cloud.github.com/assets/6134226/1700248/63abcfa8-6001-11e3-92d1-67c304842dfc.png)

**Comment by sharoonthomas** [comment]
The issue is we don't test on windows as all our clients use (or are encouraged to use) linux for production systems. 

However, if you have a pull request which fixes this and one more windows user agrees with the patch, we will be happy to merge it.

**Comment by shalabhaggarwal** [comment]
@raeftaker  Apart from what @sharoonthomas has pointed out, i see that the module name in your system is _magento_integration-develop_, which should actually be just **magento_integration**. Although I am not sure if this is the cause of the error your have posted above in screenshot.
