### ISSUE TITLE
Cofiguration change

### ISSUE THREAD

**Issue by Nivaa** [openlabs/magento_integration#166]
Hello,

Can I import Sales Order after changing the configuration of the product imported from Magento to OpenERP?

E.g. For bundled product.

Awaiting a response.

Thanks

**Comment by shalabhaggarwal** [comment]
@Nivaa What do you mean by configuration change? Where do you want to change the configuration?

**Comment by Nivaa** [comment]
Hi, 
I want to change the configuration of the bundled product from OpenERP. 

I have imported Sales Order, then changed configuration of the Product. How can I make the configuration affect to Sales Order? As the Sales orders are already imported and then I changed configuration. In that case, Sales Order does not have the changed configuration. 

Thanks

**Comment by sharoonthomas** [comment]
Records (like sale order) once created are not affected by configuration changes. So configuration must be handled with care.

**Comment by Nivaa** [comment]
Hi Sharoon, 
I have checked it and made the changes before importing products. But in some of the cases my products are getting duplicated. 
For example,
I have product with sku: 101 for site1. This product is created for site2 also with same configuration and same name.
I am trying to find out the reason but could not get it yet. Would you please help me out?
Thanks
