### ISSUE TITLE
Unable to create purchase order from sales orders

### ISSUE THREAD

**Issue by TheDailySpank** [openlabs/magento_integration#170]
In OpenERP > Sales > Sales Orders > Select a number of order numbers that start with "mag_" > More (dropdown) > Make Invoices > Create Invoices = 

"Error!

There is no Fiscal Position defined or Income category account defined for default properties of Product categories."

However, when going into a sales order and creating a partial (Invoice > Create Invoice > Some order lines > Show Lines to Invoice) and do not check the shipping option which has no product associated with it when it's imported, it will work.

If you edit the sales order so that the shipping is attached to an item (for example, a service product called "flatrate") then you are able to batch process them.

The line item in the sales order itself has no name attached to it. It just has a description of "Magento Shipping" and whatever the price was.

Am I missing a configuration setting somewhere?

**Comment by shalabhaggarwal** [comment]
@TheDailySpank You should create account properties for product categories which will be picked up by default for the sale lines which do not have a product associated.

**Comment by TheDailySpank** [comment]
Thank you. I will give that a try.

**Comment by sharoonthomas** [comment]
Closing the issue. If there is a problem please reopen the issue
