### ISSUE TITLE
How to integrate with Order Source field of OpenERP from Magento

### ISSUE THREAD

**Issue by Nivaa** [openlabs/magento_integration#172]
Hello,

How can I differentiate the orders came from Amazon/Ebay/My Store. Order Source field is having the value but without any information on that field. This field just show me the selection of Amazon/Ebay. 
Do I need to manually select?
Quick help would be appreciable. 
Thanks

**Comment by sharoonthomas** [comment]
The place would be sale.py [1]

order_data has a dictionary of the values sent from magento and the keys on the left side indicate openerp fields.

The best way to do though would be on your own module, where  you subclass create_using_magento_data [2], call the super function which will return the created sale's BrowseRecord. Write to the sale order's source field any value based on your order_data (from magento).

If you manage to do it, you can put it up as a gist for others to refer.

[1] https://github.com/openlabs/magento_integration/blob/develop/sale.py#L354
[2] https://github.com/openlabs/magento_integration/blob/develop/sale.py#L290

**Comment by Nivaa** [comment]
Thanks Sharoon.
