### ISSUE TITLE
Hidden test connection and import buttons

### ISSUE THREAD

**Issue by ndebray** [openlabs/magento_integration#174]
For Firefox 26 and Chromium 31 on Ubuntu 12.04
The four buttons "Test Connection", "Import Websites", "Import Carriers / Shipping Methods", "Import order states" are hidden in Magento -> Configuration -> Magento Instances.
Badly fixed adding the CSS rule 'overflow:auto' to <header>

**Comment by shalabhaggarwal** [comment]
Seems more like a openerp web client related issue.
