### ISSUE TITLE
bundle products

### ISSUE THREAD

**Issue by Nivaa** [openlabs/magento_integration#177]
Hello,

When I import Sales order from magento, new BoM will be created for bundle product in OpenERP everytime. The product lines will be shown in Delivery orders if I am not wrong.

I have wrong delivery order lines of bundle product from magento because of created BoM.

Why it is so?

Your quick help would be appreciated.

**Comment by sharoonthomas** [comment]
Are you describing the same issue in https://github.com/openlabs/magento_integration/issues/176 ?

**Comment by Nivaa** [comment]
Yes , same case. What can be the solution for that?

**Comment by sharoonthomas** [comment]
I am closing this task since its a duplicate. Can we continue the conversation in #176 ?
