### ISSUE TITLE
Incorrect API settings w/SOAP User and SOAP Role

### ISSUE THREAD

**Issue by samigosms** [openlabs/magento_integration#178]
I have a fresh install of Magento and OpenERP. I can install this module with no errors and run through the installation process at https://openerp-magento-connector.readthedocs.org/en/develop/configuration.html#configuration

Now when testing the connection, I get an incorrect API error. I have noted similar threads in the issues here but one was solved because they have no role. I have a role and a user assigned to that role. My key and username are correct.

The only thing I can think is that my site is a subdomain i.e. http://shop.magento.com/ and or perhaps Apache needs a restart or OpenERP server needs a restart? I don't have control to restart Apache but please let me know if there are any problems with subdomains.

**Comment by sharoonthomas** [comment]
It is probably to do with the subdomains. Why don't you test it manually if you are a programmer ?

Are there any other services which consume the site's web service api which you could test ?

**Comment by samigosms** [comment]
I did and it appears if I test with a normal site structure like magento.com/shop everything works fine for the setup (other problems elsewhere but for this it is able to set up properly.)

Testing again on shop.magento.com returns the error. It appears perhaps this module is incompatible with subdomains? It is not a giant problem for me at the moment but it could cause some headaches with others in the future. Perhaps if you can reproduce a subdomain error in a test you can add this to your documentation to note the incompatibility. Thanks.

**Comment by sharoonthomas** [comment]
@RKS213 there is no such things as incompatible with subdomains. It is usually to do with apache redirects and virtual hosts used to handle such shops. They don't usually give out the API handlers on the subdomain but just a store.

Can you try the base url of the admin (when you log into magento admin of your site ?) Is that also on a subdomain ?

**Comment by samigosms** [comment]
When I change RewriteBase in my Magento installation then the module works fine on subdomains. I can no longer reproduce the issue so it looks like this might have been a Magento issue?

**Comment by sharoonthomas** [comment]
It will be useful if you can explain what you did to get around the subdomain issue. Might help someone who finds the same issue in future.

**Comment by samigosms** [comment]
I changed to RewriteBase / in .htaccess.

**Comment by stoverjosh** [comment]
RKS213,
I am having the same issue and I am using Magento 1.8.  I have changed the line "RewriteBase /magento/" to "RewriteBase /" but the error is not resolved.  Were you working with Magento 1.7?  Did I make the change correctly?
