### ISSUE TITLE
Incorrect directory magento_integration-develop vs magento_integration

### ISSUE THREAD

**Issue by samigosms** [openlabs/magento_integration#179]
I am seeing a similar error to https://github.com/openlabs/magento_integration/issues/87#issuecomment-21413164

Basically trying to import websites returns

ValueError: No such external ID currently defined in the system: magento_integration.instance_website_tree_view

The proposed solution is to change the module directory from magento_integration-develop to magento_integration.

Once I make this change, I am having another issue where I receive an error:

KeyError: u'magento.instance'

I have restarted the OpenERP server. The documentation does not mention renaming the module directory so I don't know if this is the correct solution to the issue. Either way, each module name gives me some type of error.

**Comment by sharoonthomas** [comment]
The documentation has been updated with a warning to reflect the importance of module name.
