### ISSUE TITLE
Sale Orders imported from Magento as MakeToOrder

### ISSUE THREAD

**Issue by kenzo55** [openlabs/magento_integration#180]
When I import SO from Magento 1.7 into OpenERP 7 the procurement details for a product are set to MTO whereas the Product within OpenERP is set up as MakeToStock.

When I run schedulers from Warehouse the product quantity in stock is not checked and a PO is created although there are sufficient quantities of the product available.

How can I get procurement method to default to product record for imported SO?

**Comment by kenzo55** [comment]
Looking at sale.py the procurement method is hard coded as 'make_to_order' surely this should be determinable from magento product or at least give option to choose MTO or MTS

**Comment by shalabhaggarwal** [comment]
@kenzo55 You can subclass the method `extract_product_values_from_data()` at [1](https://github.com/openlabs/magento_integration/blob/develop/product.py#L381) and set a `procure_method` as in [2](https://github.com/openlabs/magento_integration/blob/develop/product.py#L453).

**Comment by sharoonthomas** [comment]
AFAICS, there is no way to determine if a product is MTO or MTS from magento information
