### ISSUE TITLE
Import Images

### ISSUE THREAD

**Issue by JoeVoxster** [openlabs/magento_integration#181]
Is it possible to import images form Magento?

if yes do I need to install additional module?

I finally installed magento_itegration on ubuntu 12.04 and lp:~product-core-editors/openerp-product-attributes/7.0. But I don't get images. 

Thank you in advance for your reply.

**Comment by shalabhaggarwal** [comment]
This is a duplicate of #78 

CC: @sharoonthomas

**Comment by sharoonthomas** [comment]
Closing duplicate
