### ISSUE TITLE
Tax amount, untaxed amount, total

### ISSUE THREAD

**Issue by Nivaa** [openlabs/magento_integration#186]
Hi, 

When I import Sales orders,in OpenERP Sales order total , untax amount and tax amount differs from magento. For bundle product and simple product too. 

Why it is so? Can anyone explain?

Quick help would be apprecated.

**Comment by sharoonthomas** [comment]
There are several reasons why the totals may not match including complications arising out of mismatch in taxes for which magento does not send clear information. A better approach could be to tag these orders into an exception state and then ask the user to manually process the order.

**Comment by Nivaa** [comment]
Ok. Thanks sharoon.
