### ISSUE TITLE
Export products with Images from Openerp to Magento not working

### ISSUE THREAD

**Issue by Jaydev-B** [openlabs/magento_integration#189]
When we export products from Openerp ==> Magento  images are not exporting,
it was written in the connector brief that will export images  but this function is not working,
anybody have any idea ...?

**Comment by sharoonthomas** [comment]
Image synchronization is not included, though it should be easy to implement. I could not find where we had mentioned this as a feature, could you give us a link and we will fix it.

**Comment by Jaydev-B** [comment]
Yep, it was mentioned in your OpenERP 6.0.3. version connector page 
Here==> http://www.openlabs.co.in/article/openerp-magento-connector
so I was curious that is it  possible in current version or not  because it is not exporting images.

Regards,
