### ISSUE TITLE
Why am I getting this message

### ISSUE THREAD

**Issue by renierdbruyn** [openlabs/magento_integration#199]
I am getting this message in the terminal when I start my project: 

```
[pycountry.db][MainThread] Country True already taken in index 'deleted' and will be ignored.

```

I do not know why I am getting this message?

I found this post #124 still don't understand what is causing this.

**Comment by sharoonthomas** [comment]
those are warning you could safely ignore.

**Comment by renierdbruyn** [comment]
it is slowing my system down... is there a way to disable it?

**Comment by dufferzafar** [comment]
yeah, a way of disabling these would be great

**Comment by sharoonthomas** [comment]
@renierdbruyn how is this warning message slowing your system down ? These logs appear only once when the server starts right ?

**Comment by renierdbruyn** [comment]
@sharoonthomas It was actually something else in my redis cache that was using a lot of memory, to solve it I ran the `redis-cli` command, and `flushdb`..,
