### ISSUE TITLE
importing/updating Catalog raises error if email is fetched simultaneously

### ISSUE THREAD

**Issue by ghost** [openlabs/magento_integration#209]
If, during a catalog import/update, the fetch email process runs, the server names get mixed up and the error as shown in the sceenshot is visible.
![screenshot](https://cloud.githubusercontent.com/assets/1467053/2564679/e8cb9b58-b8a5-11e3-88fb-4638e4aa27c8.png)

**Comment by sharoonthomas** [comment]
Looks like OpenERP's poor design on Cron. Fixing this is beyond the scope of this project.
