### ISSUE TITLE
images are not exproted when exporting catalog from Magento to OpenERP 

### ISSUE THREAD

**Issue by AdilAndroid** [openlabs/magento_integration#215]
When I export catalog frop OpenERP to Magento I get all products but images of products are not exported.
Is thre any solution for this issue ?

**Comment by ghost** [comment]
I am having the same issue, does this help?

import urllib2
import mock
from base64 import b64encode

from openerp.addons.magentoerpconnect.unit.import_synchronizer import (
    import_batch, import_record)
from openerp.addons.connector.session import ConnectorSession
import openerp.tests.common as common
from .common import mock_api, MockResponseImage
from .test_data import magento_base_responses
from .test_data_product import simple_product_and_images
from openerp.addons.magentoerpconnect.product import (
  CatalogImageImporter, ProductProductAdapter)

**Comment by sharoonthomas** [comment]
Image export/import is not a feature.

Read more: https://github.com/openlabs/magento_integration/wiki/Image%20Synchronization
