### ISSUE TITLE
please help me install this module in openerp setup windows 8 x64

### ISSUE THREAD

**Issue by pvd276** [openlabs/magento_integration#225]
i'm setup this module by this guide
http://openerp-magento-connector.readthedocs.org/en/latest/introduction.html
but it not working, it always have error "No handler found"

i install python 2.7 to c:\python27
i install pycountry 1.7
i install openerp in c:\openerp7

i install magento module and copy folder to C:\openerp7\Server\server
https://github.com/openlabs/magento

i download module magento_integration, extracted and rename it, copy to C:\openerp7\Server\server\openerp\addons
i run command "python setup.py install"

after that, i start openerp by http://localhost:8069/
it have error "No handler found"

how to fix it

**Comment by sharoonthomas** [comment]
The specific `magento` module is not an openerp module but a generic python API to magento.

If you need commercial support please contact the sales team at: https://openerp-magento-connector.readthedocs.org/en/develop/about_us.html#technical-support
