### ISSUE TITLE
Import Catalog issue/Usable Error message

### ISSUE THREAD

**Issue by J0s3f** [openlabs/magento_integration#227]
Hello,
when importing the Magento Catalog (for the first time) after some time it reports an error:

```
        Datenintegritäts-Fehler

        Die Aktion kann nicht fertiggestellt werden, wahrscheinlich aufgrund einer der folgenden Fehler:
        - Löschen: Sie versuchen einen Datensatz zu löschen, auf den noch andere Datensätze referenzieren
        - Neu/Aktualisierung: Ein Pflicht-Feld wurde nicht oder nicht richtig ausgefüllt

        [Objekt mit Referenz: name - name] 
```

Is there a way to get a better error message?
This site has over 4800 products, so the information that some field is not correct somewhere is not helping.

**Comment by sharoonthomas** [comment]
Could you change the language to English and report the error again ? 

I apologize I am not able to understand the error message.

**Comment by J0s3f** [comment]
Of course! Sorry!

```
Integrity Error

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: name - name] 
```

**Comment by sharoonthomas** [comment]
My guess would be you have a custom module installed which adds a required
field but not a default value for it.

Could you go through all additional modules to check for this ?

On Thursday, July 3, 2014, Josef notifications@github.com wrote:

> Of course! Sorry!
> 
> Integrity Error
> 
> The operation cannot be completed, probably due to the following:
> - deletion: you may be trying to delete a record while other records still reference it
> - creation/update: a mandatory field is not correctly set
> 
> [object with reference: name - name]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openlabs/magento_integration/issues/227#issuecomment-47950366
> .

## 

Sent from Gmail Mobile

**Comment by J0s3f** [comment]
Just to be sure: You are talking about magento Modules, not OpenERP Modules?

**Comment by sharoonthomas** [comment]
OpenERP modules

**Comment by J0s3f** [comment]
I am not quite sure how to do this?
I have very few custom Modules installed. Most are core Modules! All I have is:

| External ID | Module Name | Technical Name | Author | Latest Version |
| --- | --- | --- | --- | --- |
| base.module_account_analytic_analysis | Contracts Management | account_analytic_analysis | Camptocamp | 7.0.1.1 |
| base.module_l10n_at | Austria - Accounting | l10n_at | conexus.at | 7.0.1.0 |
| **export**.ir_module_module_209 | Magento Integration | magento_integration | Openlabs Technologies & Consulting Pvt Ltd. | 7.0.2.0dev |
| base.module_web | Web | web |  | 7.0.1.0 |
| base.module_web_calendar | Web Calendar | web_calendar |  | 7.0.2.0 |
| base.module_web_diagram | OpenERP Web Diagram | web_diagram |  | 7.0.2.0 |
| base.module_web_gantt | Web Gantt | web_gantt |  | 7.0.2.0 |
| base.module_web_graph | Graph Views | web_graph |  | 7.0.3.0 |
| base.module_web_kanban | Base Kanban | web_kanban |  | 7.0.2.0 |
| base.module_web_tests | Tests | web_tests |  | 7.0.2.0 |
| base.module_web_view_editor | View Editor | web_view_editor |  | 7.0.2.0 |
| base.module_analytic_contract_hr_expense | Contracts Management: hr_expense link | analytic_contract_hr_expense | OpenERP S.A. | 7.0.1.1 |
| base.module_account | eInvoicing | account | OpenERP SA | 7.0.1.1 |
| base.module_account_accountant | Accounting and Finance | account_accountant | OpenERP SA | 7.0.1.1 |
| base.module_account_analytic_default | Account Analytic Defaults | account_analytic_default | OpenERP SA | 7.0.1.0 |
| base.module_account_analytic_plans | Multiple Analytic Plans | account_analytic_plans | OpenERP SA | 7.0.1.0 |
| base.module_account_budget | Budgets Management | account_budget | OpenERP SA | 7.0.1.0 |
| base.module_account_chart | Template of Charts of Accounts | account_chart | OpenERP SA | 7.0.1.1 |
| base.module_account_report_company | Invoice Analysis per Company | account_report_company | OpenERP SA | 7.0.1.0 |
| base.module_account_voucher | eInvoicing & Payments | account_voucher | OpenERP SA | 7.0.1.0 |
| base.module_analytic | Analytic Accounting | analytic | OpenERP SA | 7.0.1.1 |
| base.module_analytic_user_function | Jobs on Contracts | analytic_user_function | OpenERP SA | 7.0.1.0 |
| base.module_auth_signup | Signup | auth_signup | OpenERP SA | 7.0.1.0 |
| base.module_base | Base | base | OpenERP SA | 7.0.1.3 |
| base.module_base_action_rule | Automated Action Rules | base_action_rule | OpenERP SA | 7.0.1.0 |
| base.module_base_calendar | Calendar | base_calendar | OpenERP SA | 7.0.1.0 |
| base.module_base_import | Base import | base_import | OpenERP SA | 7.0.1.0 |
| base.module_base_setup | Initial Setup Tools | base_setup | OpenERP SA | 7.0.1.0 |
| base.module_base_status | State/Stage Management | base_status | OpenERP SA | 7.0.1.0 |
| base.module_base_vat | VAT Number Validation | base_vat | OpenERP SA | 7.0.1.0 |
| base.module_board | Dashboards | board | OpenERP SA | 7.0.1.0 |
| base.module_claim_from_delivery | Claim on Deliveries | claim_from_delivery | OpenERP SA | 7.0.1.0 |
| base.module_contacts | Address Book | contacts | OpenERP SA | 7.0.1.0 |
| base.module_crm | CRM | crm | OpenERP SA | 7.0.1.0 |
| base.module_crm_claim | Claims Management | crm_claim | OpenERP SA | 7.0.1.0 |
| base.module_crm_helpdesk | Helpdesk | crm_helpdesk | OpenERP SA | 7.0.1.0 |
| base.module_decimal_precision | Decimal Precision Configuration | decimal_precision | OpenERP SA | 7.0.0.1 |
| base.module_delivery | Delivery Costs | delivery | OpenERP SA | 7.0.1.0 |
| base.module_edi | Electronic Data Interchange (EDI) | edi | OpenERP SA | 7.0.1.0 |
| base.module_fetchmail | Email Gateway | fetchmail | OpenERP SA | 7.0.1.0 |
| base.module_hr | Employee Directory | hr | OpenERP SA | 7.0.1.1 |
| base.module_hr_attendance | Attendances | hr_attendance | OpenERP SA | 7.0.1.1 |
| base.module_hr_expense | Expense Management | hr_expense | OpenERP SA | 7.0.1.0 |
| base.module_hr_timesheet | Timesheets | hr_timesheet | OpenERP SA | 7.0.1.0 |
| base.module_hr_timesheet_invoice | Invoice on Timesheets | hr_timesheet_invoice | OpenERP SA | 7.0.1.0 |
| base.module_hr_timesheet_sheet | Timesheets | hr_timesheet_sheet | OpenERP SA | 7.0.1.0 |
| base.module_mail | Social Network | mail | OpenERP SA | 7.0.1.0 |
| base.module_mrp | MRP | mrp | OpenERP SA | 7.0.1.1 |
| base.module_note | Notes | note | OpenERP SA | 7.0.1.0 |
| base.module_note_pad | Memos pad | note_pad | OpenERP SA | 7.0.0.1 |
| base.module_pad | Collaborative Pads | pad | OpenERP SA | 7.0.2.0 |
| base.module_pad_project | Pad on tasks | pad_project | OpenERP SA | 7.0.1.0 |
| base.module_portal | Portal | portal | OpenERP SA | 7.0.1.0 |
| base.module_portal_claim | Portal Claim | portal_claim | OpenERP SA | 7.0.0.1 |
| base.module_portal_crm | Portal CRM | portal_crm | OpenERP SA | 7.0.0.1 |
| base.module_portal_hr_employees | Portal HR employees | portal_hr_employees | OpenERP SA | 7.0.0.1 |
| base.module_portal_project | Portal Project | portal_project | OpenERP SA | 7.0.0.1 |
| base.module_portal_sale | Portal Sale | portal_sale | OpenERP SA | 7.0.0.1 |
| base.module_portal_stock | Portal Stock | portal_stock | OpenERP SA | 7.0.0.1 |
| base.module_process | Enterprise Process | process | OpenERP SA | 7.0.1.0 |
| base.module_procurement | Procurements | procurement | OpenERP SA | 7.0.1.0 |
| base.module_product | Products & Pricelists | product | OpenERP SA | 7.0.1.1 |
| base.module_project | Project Management | project | OpenERP SA | 7.0.1.1 |
| base.module_project_timesheet | Bill Time on Tasks | project_timesheet | OpenERP SA | 7.0.1.0 |
| base.module_purchase | Purchase Management | purchase | OpenERP SA | 7.0.1.1 |
| base.module_purchase_analytic_plans | Purchase Analytic Plans | purchase_analytic_plans | OpenERP SA | 7.0.1.0 |
| base.module_purchase_requisition | Purchase Requisitions | purchase_requisition | OpenERP SA | 7.0.0.1 |
| base.module_resource | Resource | resource | OpenERP SA | 7.0.1.1 |
| base.module_sale | Sales Management | sale | OpenERP SA | 7.0.1.0 |
| base.module_sale_analytic_plans | Sales Analytic Distribution | sale_analytic_plans | OpenERP SA | 7.0.1.0 |
| base.module_sale_crm | Opportunity to Quotation | sale_crm | OpenERP SA | 7.0.1.0 |
| base.module_sale_journal | Invoicing Journals | sale_journal | OpenERP SA | 7.0.1.0 |
| base.module_sale_mrp | Sales and MRP Management | sale_mrp | OpenERP SA | 7.0.1.0 |
| base.module_sale_stock | Sales and Warehouse Management | sale_stock | OpenERP SA | 7.0.1.0 |
| base.module_share | Share any Document | share | OpenERP SA | 7.0.2.0 |
| base.module_stock | Warehouse Management | stock | OpenERP SA | 7.0.1.1 |
| base.module_stock_invoice_directly | Invoice Picking Directly | stock_invoice_directly | OpenERP SA | 7.0.1.0 |
| base.module_warning | Warning Messages and Alerts | warning | OpenERP SA | 7.0.1.0 |
| base.module_email_template | Email Templates | email_template | OpenERP,OpenLabs | 7.0.1.1 |

**Comment by J0s3f** [comment]
I created a new empty OpenERP Database. The only Module I installed is the Magento integration.
The import results in exactly the same error!

I then installed a empty Magento installation. I can import products I create from this. So the error must be at the Magento side!
Is there a way to log the API Communication with Magento or another way to find which products have problems?

**Comment by J0s3f** [comment]
I couldn't get it to work so I switched to another OpenERP Connector (http://openerp-magento-connector.com/index.html) and it works with this!
