### ISSUE TITLE
import website error

### ISSUE THREAD

**Issue by operafr** [openlabs/magento_integration#66]
on a brand new installation of openerp it is impossible ther is a mistake on importing websites 

with the magento-integration installed today and magento  1.7.0.2

Client Traceback (most recent call last):
 File "/opt/openerp/web/addons/web/http.py", line 204, in dispatch
   response["result"] = method(self, *_self.params)
 File "/opt/openerp/web/addons/web/controllers/main.py", line 1132, in call_button
   action = self._call_kw(req, model, method, args, {})
 File "/opt/openerp/web/addons/web/controllers/main.py", line 1120, in _call_kw
   return getattr(req.session.model(model), method)(_args, **kwargs)
 File "/opt/openerp/web/addons/web/session.py", line 42, in proxy
   result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
 File "/opt/openerp/web/addons/web/session.py", line 30, in proxy_method
   result = self.session.send(self.service_name, method, *args)
 File "/opt/openerp/web/addons/web/session.py", line 103, in send
   raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
 File "/opt/openerp/web/addons/web/session.py", line 89, in send
   return openerp.netsvc.dispatch_rpc(service_name, method, args)
 File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
   result = ExportService.getService(service_name).dispatch(method, params)
 File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
   res = fn(db, uid, _params)
 File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
   return self.execute(db, uid, obj, method, *args, *_kw or {})
 File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
   return f(self, dbname, _args, *_kwargs)
 File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
   res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
 File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
   return getattr(object, method)(cr, uid, _args, *_kw)
 File "/opt/openerp/addons/magento-integration/wizard/import_websites.py", line 91, in import_websites
   return self.open_websites(cursor, user, ids, instance, context)
 File "/opt/openerp/addons/magento-integration/wizard/import_websites.py", line 107, in open_websites
   cursor, user, 'magento_integration', 'instance_website_tree_view'
 File "/opt/openerp/server/openerp/tools/cache.py", line 18, in lookup
   r = self.lookup(self2, cr, *args)
 File "/opt/openerp/server/openerp/tools/cache.py", line 46, in lookup
   value = d[key] = self.method(self2, cr, *args)
 File "/opt/openerp/server/openerp/addons/base/ir/ir_model.py", line 868, in get_object_reference
   data_id = self._get_id(cr, uid, module, xml_id)
 File "/opt/openerp/server/openerp/tools/cache.py", line 18, in lookup
   r = self.lookup(self2, cr, *args)
 File "/opt/openerp/server/openerp/tools/cache.py", line 46, in lookup
   value = d[key] = self.method(self2, cr, *args)
 File "/opt/openerp/server/openerp/addons/base/ir/ir_model.py", line 861, in _get_id
   raise ValueError('No such external ID currently defined in the system: %s.%s' % (module, xml_id))
ValueError: No such external ID currently defined in the system: magento_integration.instance_website_tree_view

File "/opt/openerp/web/addons/web/http.py", line 204, in dispatch

**Comment by shalabhaggarwal** [comment]
Thanks for reporting this issue.

It seems that you are working off an older version of the module.

Please upgrade to the latest module from develop branch and feel free to revert back if the issue persists.

**Comment by operafr** [comment]
you mean magento-integration module   i just download and reinstall  the last online module  
the issue is the same

**Comment by shalabhaggarwal** [comment]
did you do a upgrade of the module?

if the issue persists, could you try the same with a new database?

**Comment by operafr** [comment]
i reinstall the module git clone https://github.com/openlabs/magento-integration.git

delete the database 
create a new database without demodata 
in the log i could'nt install the module 
git clone https://github.com/openlabs/magento-integration.git

got this error 
ERROR test15 openerp.addons.base.ir.ir_ui_view: Can't render view  for model: magento.store.export_tier_prices
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/base/ir/ir_ui_view.py", line 126, in _check_render_view
    fvg = self.pool.get(view.model).fields_view_get(cr, uid, view_id=view.id, view_type=view.type, context=context)
AttributeError: 'NoneType' object has no attribute 'fields_view_get'
2013-07-15 12:12:23,697 24024 ERROR test15 openerp.tools.convert: Parse error in /opt/openerp/mag/magento-integration/wizard/export_tier_prices.xml:5: 

```
    <record id="view_magento_export_tier_prices" model="ir.ui.view">
        <field name="name">magento.store.export_tier_prices.form</field>
        <field name="model">magento.store.export_tier_prices</field>
        <field name="arch" type="xml">
            <form string="Export Tier Prices" version="7.0">
                <group>
                    <h3 class="oe_grey">
                        This wizard will export product tier prices to
                        magento for this store.
                    </h3>
                </group>
                <footer>
                    <button string="Continue" type="object" name="export_tier_prices"/>
                    <button string="Close" special="cancel" class="oe_link"/>
                </footer>
            </form>
        </field>
    </record>
```

Traceback (most recent call last):
  File "/opt/openerp/server/openerp/tools/convert.py", line 847, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/opt/openerp/server/openerp/tools/convert.py", line 814, in _tag_record
    id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/openerp/server/openerp/addons/base/ir/ir_model.py", line 963, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/openerp/server/openerp/addons/base/ir/ir_ui_view.py", line 103, in create
    return super(view, self).create(cr, uid, values, context)
  File "/opt/openerp/server/openerp/osv/orm.py", line 4470, in create
    self._validate(cr, user, [id_new], context)
  File "/opt/openerp/server/openerp/osv/orm.py", line 1544, in _validate
    raise except_orm('ValidateError', '\n'.join(error_msgs))
except_orm: ('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')
2013-07-15 12:12:23,698 24024 ERROR test15 openerp.netsvc: ValidateError
Error occurred while validating the field(s) arch: Invalid XML for View Architecture!
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 144, in wrapper
    raise except_osv(inst.name, inst.value)
except_osv: ('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')

**Comment by shalabhaggarwal** [comment]
We tried to regenerate this issue on multiple instances of OpenERP on fresh databases but could not regenerate the issue.

I feel the issue can be with an older revision of OpenERP being used. Can you update to the latest build of openerp and try with the same?

**Comment by operafr** [comment]
this is a fresh install on ubuntu 12.04 
with user openerp 
bzr branch lp:openobject-server/7.0 server
bzr branch lp:openobject-addons/7.0 addons
bzr branch lp:openerp-web/7.0 web

on python 2.7 

something wrong?

**Comment by shalabhaggarwal** [comment]
I am not sure what can the issue be as all the other users of this module have not reported any issues with installation.

Please try the nightly builds of openerp from http://nightly.openerp.com/7.0/nightly/src/openerp-7.0-latest.tar.gz

**Comment by operafr** [comment]
same on nightly build 

more info ubuntu 12.04 lts 64 bytes

**Comment by shalabhaggarwal** [comment]
There is only one more issue i can think of.

Can you rename the the name of the module folder to magento_integration from magento-integration?

**Comment by sharoonthomas** [comment]
I think its the issue with the module name because openerp uses the name of the folder to identify the module name. And xml records we refer to obviously uses magento_integration while a clone from github itself would give you magento-integration

**Comment by damiansoriano** [comment]
Calling the module magento-integration instead of magento_integration can bring some problemes. For example, this line:

https://github.com/openlabs/magento-integration/blob/develop/wizard/import_websites.py#L107

Will throw an error when importing website if the module is not called magento_integration. Maybe then name of the repository can be changed in order to avoid confusion.

**Comment by operafr** [comment]
since update from today it' doesnt function anymore

**Comment by shalabhaggarwal** [comment]
Please provide a detailed stacktrace or error logs about the issue you are facing.

**Comment by operafr** [comment]
the issue could be fixed with changing recursively magento_integration by magento-integration in all files 

.travis.yml:11:   - ln -s magento-integration magento_integration
setup.py:50:     name='magento_integration',
test_base.py:50:         install_module('magento_integration')
import_websites.py:107:             cursor, user, 'magento_integration', 'instance_website_tree_view'

this fix the problem for me

**Comment by shalabhaggarwal** [comment]
Thanks for the update.

We would prefer the change be done other way round and the module's folder name be changed to `magento_integration` from `magento-integration`. Everything should just work out of the box. This will also make sure that any new updates to the module do not break existing installation and there are no conflicts of code happen when pulling new changes.

**Comment by operafr** [comment]
if you change it to magento_integration you have to change the repository name because of the git clone

the files affected 

.travis.yml:11:   - ln -s magento-integration magento_integration
.travis.yml:12:   - cd magento-integration
**init**.py:3:     magento-integration
fabfile.py:46:     print "View at: http://openlabs.github.io/magento-integration"
README.rst:48: .. image:: https://travis-ci.org/openlabs/magento-integration.png?branch=develop
setup.py:52:     url='https://github.com/openlabs/magento-integration/',
**init**.py:3:     magento-integration
import_websites.py:3:     magento-integration
test_connection.py:3:     magento-integration

i hope my search help you 

many thanks for your Work

**Comment by shalabhaggarwal** [comment]
Thanks @operafr 

Your research is really commendable.

It is advised not to clone the module everytime the module has an update.

git clone is a one time process which is used to get the module the first time. Thereafter git pull should do the job.

Hence, these are the commands to be used:

First time getting the module:

```
git clone git@github.com:openlabs/magento-integration.git
mv magento-integration magento_integration [You can create a soft link using ln -s as well]
```

Next time pulling for changes:

```
This happens from inside the module folder, i.e, magento_integration
git pull origin develop
```

**Comment by shalabhaggarwal** [comment]
We have updated the repo name to `magento_integration`.

The previous repo URL will also be functional

**Comment by damiansoriano** [comment]
@shalabhaggarwal better :+1:

**Comment by shalabhaggarwal** [comment]
I will close this issue as it has been addressed by name change of repo.

Any more issues can be reported on a new issue.

Thanks @operafr @damiansoriano for your feedback. :)

**Comment by samigosms** [comment]
You should change all of your names, including your zip download file. I am fighting these same issues and getting more errors when renaming the module. I am going to have to start completely from scratch now because of errors changing the name. You call your zip file magento_integration-develop and this is what the directory is name after this. What a headache your module because you do not document these issues or provide the proper namespace for your files. I have wasted many hours tonight trying to find the solution and I will probably switch to Akretion's module in the future.

**Comment by sharoonthomas** [comment]
@RKS213 opensource is about contribution. Why don't you update the installation documentation for the good of everybody ? Happy to merge a pull request if you send one ?

**Comment by sharoonthomas** [comment]
(and to be honest, I think it sucks for openerp that it decides module name based on the name of a folder)

**Comment by samigosms** [comment]
This is true. A module name should not be dependent on it's directory. Using other platforms this seems to be the case, however, I have seen problems with that as well. I.e. you cannot find your module because they named the directory foo but called the module bar. It is pros and cons I guess. 

As for documentation, I refer to your documentation your develop send to me in an email located here: https://openerp-magento-connector.readthedocs.org/en/develop/configuration.html#configuration and I do not have access to change this documentation. If you refer to any docs on github, I have not read any of those and just look at the ones Rohit has emailed to me.

**Comment by samigosms** [comment]
I see now you have it linked to the docs on github.
