### ISSUE TITLE
Exporting from OpenERP to Magento

### ISSUE THREAD

**Issue by damiansoriano** [openlabs/magento_integration#68]
Hi there!

I was testing the Magento integration module and it seems very solid, nice job!

I found that there is no possibility to export products from OpenERP to Magento. This is a recurrent scenario, where a client that is already using OpenERP wants to go online and thus wants an ECommerce platform.

Is possible to export products from OpenERP to Magento?

If not, there are plants to make something like this?

Thanks!

Damián Soriano

**Comment by shalabhaggarwal** [comment]
Hi Damián,

This connector is designed with the concept that the tools should be used for what they are meant to be good at.

Magento is a very powerful E-commerce platform and should be used for product and attributes management while OpenERP has a strong inventory and fulfilment management system and it should be used for the same.

Hence we only support import of products from Magento to OpenERP and that too only with the details required for managing inventory and fulfilment/shipping functions.

I hope this makes sense!

**Comment by sharoonthomas** [comment]
However, we should leave this ticket open to collect feedback if this is a feature that we should develop in future. Please add a +1 if you think this feature should be developed.

**Comment by damiansoriano** [comment]
@shalabhaggarwal: yes it makes sense, but the scenario I just describe is very realistic. There is a huge amount of people using OpenERP with their products already saved there that would like to go online selling.

What do we said to them? Remove products from OpenERP and reinsert them in Magento so you can import them in OpenERP?

This will not work, usually people/companies using OpenERP have a history of the products with many relations with other objects and stored information, they would not like to remove them just to go online.

Hope this also makes thanks :)

**Comment by jjscarafia** [comment]
+1

**Comment by shalabhaggarwal** [comment]
@damiansoriano 

I understand your reasoning for this feature.
We are considering a best possible option to handle this case and also keep the underlying concept of the module also intact.

**Comment by damiansoriano** [comment]
@shalabhaggarwal Ok, thanks!

You mean handle this with an external tool or some action within the model? I am just pointing this out so the module gets better and can provides the functionality most OpenERP users are searching.

I would prefer to use this module rather that other Magento-OpenERP connectors (some of them provide 2 ways products synchronization) since the code in this module is much more clean.

**Comment by shalabhaggarwal** [comment]
@damiansoriano @jjscarafia 

This is what we propose as a solution:

We will allow export of products from OpenERP to Magento but with minimal configuration done.
All the products selected for export will be exported to a category, website chosen by the user from a wizard. The exported products will always be exported as simple products as other product types need attribute management which better be left to magento. Other required details like weight, tax class etc will be hardcoded to some default values which can later be configured on magento itself.

How does this solution sound? Does it suffice to basic needs?

**Comment by damiansoriano** [comment]
@shalabhaggarwal yes, it sound go to me. The main think is to make the link between Products in OpenERP and Products in Magento without reinserting them in Magento. This sound very reasonable.

If there are further requirements for different clients this can be implemented as a different module.

Thanks for the constant reply and consideration :)
