### ISSUE TITLE
Qty is not imported

### ISSUE THREAD

**Issue by tonaino** [openlabs/magento_integration#81]
Qty is not imported as well as the stock status (all 0 and not in stock) and if you leave the server running it will sync back to magento putting all out of sale

**Comment by shalabhaggarwal** [comment]
Hi @tonaino 

The way stock is managed on magento and openerp is quite different.

Magento just keeps a count of stock while OpenERP has a complex inventory management system to keeps track and count of stock.

Hence, its not advisable to import the stock from any external system to OpenERP.

But I understand the issue you have pointed out with the stock being synced to magento wrongly. The way to handle this would be to allow a configuration checkbox on each website in OpenERP to allow the user to choose if the stock for the products belonging to that website should be synced back to magento or not.

Also you can always disable the cron/scheduled action which exports the inventory to magento and do this manually for each website by the click of a button.

How does this solution sound? Looking forward for your feedback on this.

Thanks!

**Comment by tonaino** [comment]
Hi @shalabhaggarwal ,
both the way sounds good.. I would love to have a check box with "automatically qty update" and a button with "Manual Sync". I agree that the way to think the quantities are totally different in the two products, I was just expecting some like a first manual inventory ready made ;-)

## Anyway thank you for working on this

Antonio
