### ISSUE TITLE
error pycountry...someone pls help me

### ISSUE THREAD

**Issue by diiman2000** [openlabs/magento_integration#91]
I have downloaded pycountry-0.17 from python and run it. copied it and put in my addons folder but i still get the error no module named pycountry.. am so frustrated...please what do i do..someone help me

**Comment by sharoonthomas** [comment]
```
python setup.py install
```

is all what you need to do inside the magento_integration folder. 

You should follow the instructions on the documentation at https://openerp-magento-connector.readthedocs.org/en/develop/introduction.html#installation

**Comment by diiman2000** [comment]
thank you sharon..i hope it works..please i have 1 more major problem..i keep getting the error 'no handler found' when i try to open openerp from my browser..this has made me reinstall openerp almost 5 times in 1 day..please how do i fix it..thanks a million

**Comment by sharoonthomas** [comment]
@diiman2000 from the stack trace I think you use windows. I am not sure openerp works well on windows. If you need support why dont you hire a company to do it for you (including us) ?

I am closing this issue for now.

**Comment by diiman2000** [comment]
ok  sharoonthomas how do i go ahead with the process of hiring your company? and how much does it cost???

**Comment by shalabhaggarwal** [comment]
hi @diiman2000 

Please send an email to support@openlabs.co.in for details.

Thanks!
