### ISSUE TITLE
build/lib.linux-x86_64-2.7 does not exist..no python mobule to install????

### ISSUE THREAD

**Issue by diiman2000** [openlabs/magento_integration#93]
i get the following errow whilst installing

Warning: install_lib: build/lib.linux-x86_64-2.7 does not exist..no python mobule to install

what do i do??????

**Comment by shalabhaggarwal** [comment]
Hi @diiman2000 

Can you provide full stack trace ?

Thanks!

**Comment by diiman2000** [comment]
root@92trade:/opt/openerp/server/openerp/addons/magento_integration# python setup.py install
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to magento_integration.egg-info/requires.txt
writing magento_integration.egg-info/PKG-INFO
writing top-level names to magento_integration.egg-info/top_level.txt
writing dependency_links to magento_integration.egg-info/dependency_links.txt
reading manifest file 'magento_integration.egg-info/SOURCES.txt'
writing manifest file 'magento_integration.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying magento_integration.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/magento_integration-0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing magento_integration-0.1-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/magento_integration-0.1-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/magento_integration-0.1-py2.7.egg
Extracting magento_integration-0.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
magento-integration 0.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/magento_integration-0.1-py2.7.egg
Processing dependencies for magento-integration==0.1
Searching for pycountry==0.17
Best match: pycountry 0.17
Processing pycountry-0.17-py2.7.egg
pycountry 0.17 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pycountry-0.17-py2.7.egg
Searching for magento==0.4
Best match: magento 0.4
Processing magento-0.4-py2.7.egg
magento 0.4 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg
Searching for itsbroken==0.2
Best match: itsbroken 0.2
Processing itsbroken-0.2-py2.7.egg
itsbroken 0.2 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/itsbroken-0.2-py2.7.egg
Searching for suds==0.4.1
Best match: suds 0.4.1
Adding suds 0.4.1 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for magento-integration==0.1
root@92trade:/opt/openerp/server/openerp/addons/magento_integration#

**Comment by shalabhaggarwal** [comment]
Despite that warning, I see that all the dependencies are installed correctly. Does this cause any issues in the working of module?

**Comment by diiman2000** [comment]
no.that is the thing..the module does not show up in the app list...i have put the module in the addon folder and run it..but it still does not show up. is there anything i am doing wrong ??

**Comment by shalabhaggarwal** [comment]
The module should show up in the openerp module list even if `python setup.py install` is not run. This command is essential for installing dependencies.

Can you make sure the addons path where you have placed the module folder is same as the one which reflects in the logs when openerp server is run.?

**Comment by diiman2000** [comment]
yes it is the same. what i did was place  it in the addon folder with other modules. (magento_integration) which is the right part.. but cant still see it in openerp even after updating module list etc..

is there anything i am not doing right as i have done everything possible so far..pls help

**Comment by diiman2000** [comment]
or id it because of the error i mentioned earlier that i cant see in in openerp apps?

**Comment by shalabhaggarwal** [comment]
@diiman2000 I am not sure what might be the exact cause of this issue. I would advice to hire a company for support and setup.

**Comment by diiman2000** [comment]
is there a guide on how to install this module somewhere that i can follow? thanks

**Comment by shalabhaggarwal** [comment]
Yes, everything is well documented here https://openerp-magento-connector.readthedocs.org/en/develop/

**Comment by diiman2000** [comment]
ok thanks..last question..how do i  update the addons path to add this module’s parent folder in their server config file.]  just run me through step by step.cheers

**Comment by sharoonthomas** [comment]
The question is out of the scope of the project.

**Comment by SMorph** [comment]
I encountered the same problem, the solution is found: in OpenERP need to give the user a "Technical features" in the "Setting" - "Users" on access rights tab. Then the modules appears "Update module list".
